"""Integration checks against the real checked-in fixtures/symbol_table.parquet.
Offline — reads the file already generated by scripts/build_symbol_table.py, no
network call happens in this test suite.
"""

from px.resolve.resolver import resolve_holdings
from px.resolve.table import DEFAULT_TABLE_PATH, load_symbol_table
from px.schemas.analyze import Holding


def test_fixture_exists():
    assert DEFAULT_TABLE_PATH.exists()


def test_table_loads_and_has_a_realistic_row_count():
    table = load_symbol_table()
    assert len(table) > 5000


def test_aapl_resolves_as_a_stock():
    table = load_symbol_table()
    result = resolve_holdings([Holding(ticker="AAPL", weight=1.0)], table)

    assert result.resolved[0].ticker == "AAPL"
    assert result.resolved[0].is_etf is False


def test_spy_resolves_as_an_etf():
    table = load_symbol_table()
    result = resolve_holdings([Holding(ticker="SPY", weight=1.0)], table)

    assert result.resolved[0].ticker == "SPY"
    assert result.resolved[0].is_etf is True


def test_berkshire_share_classes_resolve_independently():
    table = load_symbol_table()
    result = resolve_holdings(
        [Holding(ticker="BRK.A", weight=0.5), Holding(ticker="BRK.B", weight=0.5)],
        table,
    )

    assert [r.ticker for r in result.resolved] == ["BRK.A", "BRK.B"]
    assert result.excluded == ()


def test_bare_berkshire_ticker_is_ambiguous_between_real_share_classes():
    table = load_symbol_table()
    result = resolve_holdings([Holding(ticker="BRK", weight=1.0)], table)

    assert result.resolved == ()
    assert result.excluded[0].reason == "ambiguous"
    assert set(result.excluded[0].candidates) == {"BRK.A", "BRK.B"}


def test_google_and_alphabet_class_a_never_cross_match_in_the_real_table():
    table = load_symbol_table()
    result = resolve_holdings(
        [Holding(ticker="GOOG", weight=0.5), Holding(ticker="GOOGL", weight=0.5)],
        table,
    )

    assert [r.ticker for r in result.resolved] == ["GOOG", "GOOGL"]
    assert result.excluded == ()
